### ISSUE TITLE
BlockState Crash on MOD Blocks / 模組方塊導致 BlockState 異常崩潰

### ISSUE THREAD

**Issue by oldip** [MohistMC/MohistNeo#102]
##  Environment / 環境資訊

- **Server Core / 伺服器核心**: `Youer-1.21.1` (`youer-1.21.1-817d047`, `youer-1.21.1-aac09ac`)
- **Plugins / 插件**:
  - `GGintegrity-1.3.8`
  - `mcMMO v2.2.041-SNAPSHOT`
- **MODs involved / 涉及模組**:
  - `Gravestone Mod`
  - `MrCrayfish's Furniture Mod: Refurbished`
  - `Iron Chests`
  - `Iron Shulker Boxes`

---

##  Problem Summary / 問題說明

When interacting with blocks from these MODs (break, place, right-click, left-click), plugins throw an `IllegalStateException` due to unsupported BlockState creation.

與上述模組的方塊互動（例如破壞、放置、點擊）時，插件會因為 `BlockState` 無法正確建立而噴出 `IllegalStateException` 錯誤。

---

### ◆ mcMMO - BlockDamageEvent (GRAVESTONE_GRAVESTONE)

```
Could not pass event BlockDamageEvent to mcMMO v2.2.041-SNAPSHOT
java.lang.IllegalStateException: Unexpected BlockState for GRAVESTONE_GRAVESTONE
    at com.google.common.base.Preconditions.checkState(Preconditions.java:601)
    at org.bukkit.craftbukkit.block.CraftBlockStates$1.createBlockState(CraftBlockStates.java:123)
    at org.bukkit.craftbukkit.block.CraftBlock.getState(CraftBlock.java:328)
    ...
```

### ◆ GGintegrity - PlayerInteractEvent (IRONCHEST_DIAMOND_CHEST)

```
Could not pass event PlayerInteractEvent to GGintegrity v1.3.8
java.lang.IllegalStateException: Unexpected BlockState for IRONCHEST_DIAMOND_CHEST
    at com.google.common.base.Preconditions.checkState(Preconditions.java:601)
    at org.bukkit.craftbukkit.block.CraftBlockStates$1.createBlockState(CraftBlockStates.java:123)
    at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:307)
    at org.bukkit.craftbukkit.block.CraftBlock.getState(CraftBlock.java:328)
    at GGintegrity.util.helpers.BlocksUtil.isContainer(BlocksUtil.java:10)
    ...
```

### ◆ mcMMO - PlayerInteractEvent (IRONCHEST_DIAMOND_CHEST)

```
Could not pass event PlayerInteractEvent to mcMMO v2.2.041-SNAPSHOT
java.lang.IllegalStateException: Unexpected BlockState for IRONCHEST_DIAMOND_CHEST
    at com.google.common.base.Preconditions.checkState(Preconditions.java:601)
    at org.bukkit.craftbukkit.block.CraftBlockStates$1.createBlockState(CraftBlockStates.java:123)
    at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:307)
    at org.bukkit.craftbukkit.block.CraftBlock.getState(CraftBlock.java:328)
    at com.gmail.nossr50.listeners.PlayerListener.onPlayerInteractMonitor(PlayerListener.java:883)
    ...
```

---

##  Root Cause / 問題根源

When plugins call:

```java
BlockState state = block.getState();
```

on modded blocks (e.g. `GRAVESTONE_GRAVESTONE`, `IRONCHEST_GOLD_CHEST`), `CraftBlockStates` cannot handle them properly, resulting in a crash.

插件在模組方塊上呼叫 `block.getState()` 時，`CraftBlockStates` 無法處理這些非原版方塊，因此崩潰。

---

##  Suggested Fix / 建議解法

Add a try-catch wrapper to all `block.getState()` calls:

在所有 `block.getState()` 呼叫加上 try-catch：

```java
try {
    BlockState state = block.getState();
    ...
} catch (IllegalStateException e) {
    return false; // or skip, or fallback logic
}
```

---

##  Reproducibility / 重現方式

1. Install one of the listed MODs 安裝任一上述模組  
2. Interact with its blocks 使用該模組方塊進行互動（破壞、放置、點擊）  
3. Observe server log 錯誤會在伺服器控制台中出現  
4. Furniture power system will also fail 家具模組的電力連線功能會失效  

---

##  Impact / 影響

- Console spam 控制台被錯誤訊息洗版
- Furniture mod's wrench linking fails 家具模組無法正常連接電力
- Server performance degraded or unstable 整體穩定性下降

---

##  Request / 請求

Please make the plugin(s) compatible with MOD blocks by handling `block.getState()` safely.

請讓插件相容 MOD 方塊，處理 `block.getState()` 時加上容錯。

---

Thanks for your hard work!  
感謝你們的努力維護！

**Comment by Mgazul** [comment]
Fixed

**Comment by oldip** [comment]
MrCrayfish's Furniture Mod: Refurbished

問題已修復，伺服器不再報錯，但實際功能仍有異常。使用扳手嘗試連接發電機與電器時無反應或無法成功連接。請確認是否有初始化錯誤或模組內部邏輯未啟用。謝謝！

The crash issue has been resolved — no more server errors — however, functionality is still broken. Using the wrench to connect generators and devices does not work. There is no visible reaction and the link does not establish. Please check if internal logic or module initialization failed silently. Thanks!
